
name: Depoly Github Pages

on:
  # 提交到master分支触发
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
      
      # 设置node版本
      - name: Set Node Version
        uses: actions/setup-node@v3
        with: 
          node-version: 16
        
      # 打包
      - name: Build
        run: npm install && npm run build

      # 部署到gh-pages
      - name: Depoly
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with: 
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
